
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package minibrowsermulti;

import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLFrameHyperlinkEvent;

/**
 *
 * @author BALL
 */
public class MiniBrowserJframe extends javax.swing.JFrame  {

    /**
     * Creates new form MiniBrowserJframe
     */
    public MiniBrowserJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        urlNameA = new java.awt.TextField();
        urlNameB = new java.awt.TextField();
        buttonSubmit = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayPageA = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayPageB = new javax.swing.JEditorPane();
        outputA = new java.awt.TextArea();
        outputB = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pawee Petchruk s4050915@kmitl.ac.th  - Assignment #2");

        jLabel1.setText("URL1: ");

        jLabel2.setText("URL2:");

        urlNameA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlNameAActionPerformed(evt);
            }
        });

        buttonSubmit.setLabel("GET PAGE");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        displayPageA.setEditable(false);
        displayPageA.setContentType("text/html;charset=utf-8"); // NOI18N
        displayPageA.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                displayPageAHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(displayPageA);

        displayPageB.setEditable(false);
        displayPageB.setContentType("text/html;charset=utf-8"); // NOI18N
        displayPageB.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                displayPageBHyperlinkUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(displayPageB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urlNameA, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                            .addComponent(outputA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(outputB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urlNameB, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(buttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(urlNameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(urlNameB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlNameAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlNameAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlNameAActionPerformed

    public void showPageByThread(String txt,int win){
        
        if(win==1)
        {
            try {
                displayPageA.setPage(txt);
            } catch (IOException ex) {
                Logger.getLogger(MiniBrowserJframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        } else   {
            try {
                displayPageB.setPage(txt);
            } catch (IOException ex) {
                Logger.getLogger(MiniBrowserJframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
            
    }//end showPageByThread
    
    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        URL verifiedUrlA = verifyUrl(urlNameA.getText());       //check a
        URL verifiedUrlB = verifyUrl(urlNameA.getText());       //check b
        
            if (verifiedUrlA != null ) {
   
                MyThread thrd1=new MyThread(urlNameA.getText(),1,this);
                thrd1.setName("THREAD #1");
                thrd1.start();

            }else{
                 JOptionPane.showMessageDialog(this, "Invalid URL A","Error", JOptionPane.ERROR_MESSAGE);
            }

            
            if (verifiedUrlB != null ) {
            
                MyThread thrd2=new MyThread(urlNameB.getText(),2,this);
                thrd2.setName("THREAD #2");
                thrd2.start();

            }else{
                 JOptionPane.showMessageDialog(this, "Invalid URL B ","Error", JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_buttonSubmitActionPerformed

    public void appendOutputA(String txt)
    {
            outputA.append(txt+"\n");
    }
    
    public void appendOutputB(String txt)
    {
            outputB.append(txt+"\n");
    }    
    
    private void displayPageAHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_displayPageAHyperlinkUpdate
                        HyperlinkEvent.EventType eventType = evt.getEventType();
        if (eventType == HyperlinkEvent.EventType.ACTIVATED) {
            if (evt instanceof HTMLFrameHyperlinkEvent) {
                HTMLFrameHyperlinkEvent linkEvent =
                        (HTMLFrameHyperlinkEvent) evt;
                HTMLDocument document =
                        (HTMLDocument) displayPageA.getDocument();
                document.processHTMLFrameHyperlinkEvent(linkEvent);
            } else {
                try {
                    displayPageA.setPage(evt.getURL());
                
                    urlNameA.setText(evt.getURL().toString());
                } catch (IOException ex) {
                    Logger.getLogger(MiniBrowserJframe.class.getName()).log(Level.SEVERE, null, ex);
                }

                
            }
             
        }
    }//GEN-LAST:event_displayPageAHyperlinkUpdate

    private void displayPageBHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_displayPageBHyperlinkUpdate
         HyperlinkEvent.EventType eventType = evt.getEventType();
        if (eventType == HyperlinkEvent.EventType.ACTIVATED) {
            if (evt instanceof HTMLFrameHyperlinkEvent) {
                HTMLFrameHyperlinkEvent linkEvent =
                        (HTMLFrameHyperlinkEvent) evt;
                HTMLDocument document =
                        (HTMLDocument) displayPageB.getDocument();
                document.processHTMLFrameHyperlinkEvent(linkEvent);
            } else {
                try {
                    displayPageB.setPage(evt.getURL());

                    urlNameB.setText(evt.getURL().toString());
                } catch (IOException ex) {
                    Logger.getLogger(MiniBrowserJframe.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
             
        }
    }//GEN-LAST:event_displayPageBHyperlinkUpdate

    
        private URL verifyUrl(String url) {
        // Only allow HTTP URLs.
        if (!(url.toLowerCase().startsWith("http://")||url.toLowerCase().startsWith("https://")))
            return null;
        
        // Verify format of URL.
        URL verifiedUrl = null;
        try {
            verifiedUrl = new URL(url);
        } catch (Exception e) {
            return null;
        }
        
        return verifiedUrl;
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniBrowserJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniBrowserJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniBrowserJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniBrowserJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniBrowserJframe().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonSubmit;
    private javax.swing.JEditorPane displayPageA;
    private javax.swing.JEditorPane displayPageB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.TextArea outputA;
    private java.awt.TextArea outputB;
    private java.awt.TextField urlNameA;
    private java.awt.TextField urlNameB;
    // End of variables declaration//GEN-END:variables

    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}


